version: "1.0"
projectName: VLI_PoCProject
runtimes:
- runtimeAlias: EdgeRuntimeOracle
  assets:
  - name: fld_113323404_stage00.projects.fl0a86a876fb144ced80484280ac1008d8.integrations:soapOrderRequestInterface
    type: flow
    stepId: /0
    reference: fld_113323404_stage00.projects.fl0a86a876fb144ced80484280ac1008d8.WmPackageServiceProvider.project.vli_poc.integrations:soapOrderRequest
  - name: OrderRequest
    type: REST
    path: /order-request
    action: POST
    reference: fld_113323404_stage00.projects.fl41e0a40b66b24415a9f1636d144caac1.WmPackageServiceProvider.project.vli_poc.integrations:restOrderRequest
