version: "1.0"
info:
  model: int-scaffold
packages:
- name: VLI_PoCProject
  gitServerName: git_andrebarbosa
  gitUrl: https://github.com/andresousabarbosa
  gitUsername: andresousabarbosa
  gitBranch: main
