version: "1.0"
info:
  model: int-scaffold
packages:
- name: VLI_PoCProject
  gitServerName: git_andrebarbosa
  gitUrl: https://github.com/andresousabarbosa
  gitUsername: andresousabarbosa
  gitBranch: main
- name: PartnerIntegration
  version: "1.0"
  gitServerName: git_andrebarbosa
  gitUrl: https://github.com/andresousabarbosa
  gitUsername: andresousabarbosa
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
  wpmVersion: v10.3.10.25
- name: WmMicrosoftAzureStorageProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
  wpmVersion: v12.0.0
